[package]
name = "climom"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
core-foundation = "0.9.3"
core-foundation-sys = "0.8.3"
coreaudio-rs = { version = "0.11.2", path = "../../coreaudio-rs" }